### ISSUE TITLE
key is not defined

### ISSUE THREAD

**Issue by ohabash** [renhongl/json-viewer-js#8]
I am trying to recreate your demo... It looks like everything is going well until the foreach where i see the following

> PartsTableComponent.html:153 ERROR ReferenceError: key is not defined

it refers to this

```
JsonViewer.prototype.forEach = function (obj, fn) {
    if (isUndefined(obj) || isNull(obj)) {
        return;
    }
    if (typeof obj === 'object' && isArray(obj)) {
        for (let i = 0, l = obj.length; i < l; i++) {
            fn.call(null, obj[i], i, obj);
        }
    } else {
        console.log('key :', key);
        for (key in obj) {
            if (obj.hasOwnProperty(key)) {
                fn.call(null, obj[key] || 'null', key, obj);
            }
        }
    }
}
```

in my html the following is outputed in the given element 

![Screen Shot 2021-01-17 at 12 59 17 PM](https://user-images.githubusercontent.com/15847500/104853025-d0360400-58c3-11eb-86fa-100baf6f7acf.png)

**Comment by ohabash** [comment]
I really cant see where key is supposed to come from `for (key in (obj)) {`

**Comment by xeroxstar** [comment]
Same here, i guess this module is not maintained ....

**Comment by renhongl** [comment]
> Same here, i guess this module is not maintained .... I just added `let` before key and it worked:
> 
> ```
> for (let key in obj) {
>             if (obj.hasOwnProperty(key)) {
>                 fn.call(null, obj[key] || 'null', key, obj);
>             }
>         }
> ```
Thank you for your answer, its first time someone used my library and ask the error. I forgot it, so sorry.
